config/routes.rb
CloudBnb::Application.routes.draw do
  root :to => "main#index", via: :get

  devise_for :users
  resources :users, only: [:show]
  resources :properties
  resources :rentals
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    elsif user.owner? || user.renter?
      can :read, :all
      can :create, Property, Rental
      can :update, Property do |property|
        property.try(:user) == user
      end
      can :destroy, Property do |property|
        property.try(:user) == user
      end
    else
      can :read, :all
    end
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user, :foreign_key => :owner_id
  has_attached_file :image, :styles => { :medium => "300>x300", :thumb => "150>x150"}, :default_url => ActionController::Base.helpers.asset_path("assets/missing_:style.jpg"), :whiny => true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  def owner
    self.user
  end
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :user, foreign_key: :renter_id
  belongs_to :property

  def renter
    self.user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties, :foreign_key => :owner_id
  has_many :rentals, :foreign_key => :renter_id

  def rental_properties
    self.rentals.map { |r| r.property }.uniq
  end

  def admin?
    self.admin
  end

  def renter?
    self.renter
  end

  def owner?
    self.owner
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :location
    devise_parameter_sanitizer.for(:account_update) << :name << :location
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @properties = Property.order(:created_at).to_a
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
  end

  def show
    @property = Property.find(params[:id])
    @rental = Rental.new
    @current_rentals = []
    @current_start_month = Date.today.month
    @current_end_month = @current_start_month
    @start_month_name = Date::MONTHNAMES[@current_start_month]
    @end_month_name = Date::MONTHNAMES[@current_end_month]

    Rental.where(property_id: @property.id).each do |rental|
      (rental.start_date..rental.end_date - 1).each{ |date| @current_rentals << date }
    end
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.create(property_params)
    if @property.save
      redirect_to property_path(@property)
    else
      render "new"
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to user_path(@property.owner)
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to property_path(@property)
    else
      render 'edit'
    end

  end

private
  def property_params
    params.require(:property).permit(:name, :price, :location, :owner_id, :description, :image)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(property_id: rental_params[:property_id],
                         start_date: Date.strptime(rental_params[:start_date], "%m/%d/%Y"),
                         end_date: Date.strptime(rental_params[:end_date], "%m/%d/%Y"))
    if @rental.save
      current_user.rentals << @rental
      redirect_to :back
    else
      render "new"
    end
  end

private
  def rental_params
    params.require(:rental).permit(:property_id, :start_date, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloud B &amp; B</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-default">
  <span class="logo"><%=link_to "Cloud B & B", root_path %></span>
  <div class="pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= link_to "#{current_user.name}", user_path(current_user), id: "current-user-name" %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-danger' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-danger' %> |
      <%= link_to "Login", new_user_session_path, :class => 'btn btn-danger' %>
    <% end %>
    <%= yield(:navigation) %>
  </div>
</nav>

<div class="container">
  <%= yield(:header) %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div id="left-col" class="pull-left">
  <div class="tagline">Welcome</div>
</div>

<div id="right-col" class="pull-right">
  <ul class="well">
    <% @properties.reverse.each do |property| %>
      <li><%= link_to image_tag(property.image.url(:medium)), property_path(property) %></li>
    <% end %>
  </ul>
</div>

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :multipart => true } do |f| %>
<div class="form-group">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</div>
<div class="form-group">
  <%= f.label :description %><br/>
  <%= f.text_area :description %>
</div>
<div class="form-group">
  <%= f.label :price %><br/>
  <%= f.number_field :price, :step => 'any' %>
</div>
<div class="form-group">
  <%= f.label :location %><br/>
  <%= f.select :location, options_for_select([["Portland"], ["New York"], ["Seattle"]]) %>
</div><br/>

<div class="form-group">
  <%= f.label :image, "Photo of your property: "%>
  <%= f.file_field :image %>
</div>

  <%= f.hidden_field :owner_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/properties/edit.html.erb
<h1>Edit <%= @property.name %></h1>

<div class="form">
  <%= render('form') %>
</div>

app/views/properties/new.html.erb
<h1>Add a listing</h1>

<div class="form">
  <%= render('form') %>
</div>

app/views/properties/show.html.erb
<%= content_for(:header) do %>
  <h2><%= @property.name %></h2>
<% end %>

<div class="row">

<div class="col col-md-6">
  <%= image_tag @property.image.url(:medium) %>
</div>
<div class="col col-md-6 gen-info">
  <h4><%= @property.description %></h4>
  <p>Price: $<%= @property.price %> per night</p>
  <p>Location: <%= @property.location %></p>
  <p>Owner: <%= link_to "#{@property.owner.name}", user_path(@property.owner) %></p>

  <% if current_user %>
    <p>Your rentals for this property: </p>
    <ul>
    <% current_user.rentals.each do |rental| %>
      <% if rental.property_id == @property.id %>
        <li>From <%= rental.start_date %> to <%= rental.end_date %></li>
      <% end %>
    <% end %>
    </ul>
  <% end %>
  <br/>

  <% if can? :destroy, @property %>
    <%= link_to "Delete this Property", property_path(@property), :class => 'btn btn-danger', :data => {:confirm => "Are you sure you wish to delete this listing?", :method => "delete"} %>
    <% end %>
  <% if can? :update, @property %>
  <%= link_to "Edit this property", edit_property_path(@property), :class => 'btn btn-danger' %>
  <% end %>
</div>
</div>


<button class="btn btn-danger" id="see-rental-form">Rent this property</button>

<br/>

<div id="rental-form">
  <%= render 'rentals/form' %>
</div>

<br/>
<script type="text/javascript">
  $(document).ready(function(){
    $('.start').click(function(){
      $('.start').removeClass("active_date");
      $(this).addClass("active_date");
      $('#rental_start_date').val($(this).attr('id'));
    });

    $('.end').click(function(){
      $('.end').removeClass("active_date");
      $(this).addClass("active_date");
      $('#rental_end_date').val($(this).attr('id'));
    });

    $('#see-rental-form').click(function() {
      if ("<%=current_user%>" !== "") {
        $(this).hide();
        $('#rental-form').show();
      } else {
        window.location.href = "<%= new_user_registration_path %>";
      }
    });
  });
</script>

app/views/properties/show.js.erb
$(document).ready(function(){
  $('#rental-form').html(<%= j render('rentals/form') %>)
});

app/views/rentals/_form.html.erb
<%= form_for @rental do |f| %>
  <div class="date-choice">
    <div class="panel panel-default">

      <div class="panel-heading">Check-in</div>

      <h4>
        <span id="start_month_left_arrow"> < </span>
        <%= @start_month_name %>
        <span id="start_month_right_arrow"> > </span>
      </h4>

      <table id="start-date" class="panel-body calendar">
          <% 1.upto(Time.days_in_month(@current_start_month)) do |day| %>
            <% full_date = "#{@current_start_month}/#{day}/2014" %>

            <% if day % 7 == 1 %>
              <tr>
            <% end %>

            <% if @current_rentals.include?(Date.strptime(full_date, '%m/%d/%Y')) %>
              <td class="unclickable"><%= " #{day}"[-2..-1] %></td>
            <% else %>
              <td id="<%= full_date %>" class="clickable start"><%= " #{day}"[-2..-1] %></td>
            <% end %>

            <% if day % 7 == 0 %>
              </tr>
            <% end %>
          <% end %>
        </table>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Check-out</div>

      <h4>
        <span class="month_left_arrow"> < </span>
        <%= @end_month_name %>
        <span class="month_right_arrow"> > </span>
      </h4>

      <table id="end-date" class="panel-body calendar">

        <% 1.upto(Time.days_in_month(@current_end_month)) do |day| %>
          <% full_date = "#{@current_end_month}/#{day}/2014" %>

          <% if day % 7 == 1 %>
            <tr>
          <% end %>

          <% if @current_rentals.include?(Date.strptime(full_date, '%m/%d/%Y')) %>
            <td class="unclickable"><%= day %></td>
          <% else %>
            <td id="<%= full_date %>" class="clickable end"><%= day %></td>
          <% end %>

          <% if day % 7 == 0 %>
              </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <%= f.hidden_field :start_date, value: nil %>
  <%= f.hidden_field :end_date, value: nil %>
  <%= f.hidden_field :property_id, value: @property.id %><br/>
  <%= f.submit "Rent!", :class => 'btn btn-danger' %>
<% end %>

app/views/users/show.html.erb
<%= content_for(:header) do %>
  <h1><%= @user.name %></h1>
<% end %>

<h3>Properties</h3>
<% @user.properties.each do |property| %>
  <p>
    <%= image_tag property.image.url(:thumb) %>
    <%= link_to "#{property.name}", property_path(property) %>
  </p>
<% end %>

<% if @user == current_user %>
  <%= link_to "Add a new listing", new_property_path, :class => 'btn btn-danger' %>
<% end %>